# Generated by Django 5.0.7 on 2024-07-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Идентификатор ссылки'),
            preserve_default=False,
        ),
    ]
