# Generated by Django 5.0.7 on 2024-07-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_menu_options_menu_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
